### PR TITLE
Mscodecoverage

### PR DESCRIPTION
**Pull request by mschnelte**
Adding support for microsoft's code coverage.
Can be enabled via options.
Coverage settings are controlled via fineCodeCoverageSettings.xml file that is created on first test run if ms code coverage option is enabled.

### CODE REVIEW

**Comment by tonyhallett** [comment]
@mschnelte Thanks.  WIll have a look tomorrow.

**Comment by tonyhallett** [comment]
@mschnelte Adding some commits now

**Comment by mschnelte** [comment]
> At the moment only the test assembly is excluded ( all in one runsettings to be used by all test projects ). FCC does more than that.

I am aware of it. But aren't the settings in FCC coverlet specific? If you feel it's worth the trouble mapping them feel free to do this. For me it would be good enough to edit the fineCodeCoverage.xml template as stated in the description of the PR.

What I do not like about the FCC options is the fact that they are not solution specific. Using the template for that would make it solution specific. I would favor that over global options. But of course nothing is stopping us to mix both approaches.

> I have the code that I used to demonstrate the idea ( [#214 (comment)](https://github.com/FortuneN/FineCodeCoverage/issues/214#issuecomment-1038362976) ) that can be merged with your existing code. It also refactors FCCEngine so that FCCEngine is ignorant to ms coverage.

What you are showing there was how I started. Simply collecting the coverage files if runsettings are set. I guess that is a use case that should be supported. But don't forget that runsettings might not contain a CoverageCollector - and I guess that is currently the majority of runsettings given the fact how new the microsoft code coverage support is. In those cases the user's runsettings might need to be altered to include coverage. One workflow could be:

1. Test are started
2. fcc detects runsettings without a code coverage collector
3. fcc asks the user if the existing runsettings shall be enhanced to include code coverage collectors
4. optional: old runsettings are backed up

**Comment by tonyhallett** [comment]
Sorry for not responding today but I have been dotPeek-ing the test explorer source looking for the optimum solution.

**Comment by mschnelte** [comment]
> Sorry for not responding today but I have been dotPeek-ing the test explorer source looking for the optimum solution.

No worries. I will most probably not be very responsive either until beginning of next week.

**Comment by tonyhallett** [comment]
There is more that I will do in the next couple of days.  Committing now that you can see where I am going with this.

This now works if the dev provides runsettings or not.  If not runsettings are created for each project with includes / excludes being determined in a similar manner to pre ms code coverage.  I have added new FCC options that can be provided globally or on a project basis as before. ( I will add the concept of solution options that will apply to ms code coverage and the old way soon ). If desired a template can be provided ( found by naming convention in project / solution folder ) that will be used with string replacement as before.  The dev can also provide runsettings that can participate in string replacement too.

**Pull request merged**
