### PR TITLE
Run coverage in parallel with tests and prevent coverage based on test failure and number of tests ( via vs options )

### PR DESCRIPTION
**Pull request by tonyhallett**

### CODE REVIEW

**Comment by tonyhallett** [comment]
close #56

**Comment by tonyhallett** [comment]
Also helps to some degree #27.

**Comment by FortuneN** [comment]
@tonyhallett Please summarize what this does. I will also check it out before release.

**Comment by tonyhallett** [comment]
There are now 3 new Visual Studio options.

RunInParallel

Nice and simple.  If set to true we do not wait until `TestOperationStates.TestExecutionFinished`

The other two work against additional information obtained through reflection.

RunWhenTestsExceed

This works for parallel and non parallel.  e.g set to 1 and when you run a single test we do not run coverage.  

> Also helps to some degree #27.

`if(operation.TotalTests <= settings.RunWhenTestsExceed){return}`

RunWhenTestsFail - non parallel only
if (!settings.RunWhenTestsFail && operation.Response.FailedTests>0){return}

--
The other change is that when a test is cancelled we cancel coverage.
```
if (e.State == TestOperationStates.TestExecutionCanceling)
{
	StopCoverageProcess();
}
```

**Comment by tonyhallett** [comment]
I will create a new pull request to replace this one in due course.

**Pull request closed without merging**
