### PR TITLE
prevent exception on locked files

### PR DESCRIPTION
**Pull request by tonyhallett**
@FortuneN This does not prevent the real problem of locked dlls preventing coverlet from working.  I am getting unable to instrument module and unable to restore due to locking.  

To see the issue fork ReflectObject.  Run a single test ( not performance ) then when you see that FCC has started coverlet run the test again.

I don't know why the re-introduction of a slightly amended file synchronization does not work.

Your thoughts ?

### CODE REVIEW

**Comment by tonyhallett** [comment]
@FortuneN I think I have a solution will post shortly

**Comment by FortuneN** [comment]
@tonyhallett 
Please solve conflict.
I will merge as soon as

**Comment by tonyhallett** [comment]
@FortuneN Be there shortly

**Comment by tonyhallett** [comment]
This change has appeared to fix the issue that I had.  It is possible that the problem is intermittent though.  Please check the changes that I have made.  If you agree then at some point a refactoring is in order !

With respect to coverlet.
When a test is run whilst FCC is running coverlet, we cancel coverlet and coverlet will not get to RestoreOriginalModules.  When FCC runs again the dll's will not pass file synchronization and will be copied again.

**Comment by FortuneN** [comment]
> When a test is run whilst FCC is running coverlet, we cancel coverlet and coverlet will not get to RestoreOriginalModules. When FCC runs again the dll's will not pass file synchronization and will be copied again

Synching is a dirty and messy enterprise (which i why i opted for a 'soft 'sync) but it's either way.
If only we could master 2 things we would be in a (by far) better position
- An effective and reliable way of detecting (and reacting to the BUILD START event)
- An effective and reliable  to kill the processes we spawn
On the face of it, it seems like this should be simple

**Comment by tonyhallett** [comment]
Killing the processes is simple - just use the cancellation token !

**Comment by FortuneN** [comment]
Are we ready to release this one?

**Comment by tonyhallett** [comment]
I think so.  There will be a better way to write the code but for now it achieves the goal.
If you run a test and fcc runs the course then the report is generated as normal.
If you run a test while fcc is running then if we are at the coverage stage then it is cancelled and the report generator is not executed - and we begin again.
If we are at the report stage then that is cancelled and we begin again.

I have tested it against the ReflectObject soln which was having issues and it is now consistently cancelling and starting again.
If you have a large repo that you could run it against - cancel FCC mid progress - and you get the expected results then I would say proceed.

**Pull request merged**
